# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a4008331051f2a197753b2f8751547686db0fa85d69c92ed4f1a1872c5c98ab92af70163817044db58da2f512f9e25b8016f03ae43db5adbb354185e4eb23b

test:
  secret_key_base: f9c22e1e4145fdb74c433092e71adace4ddbe0d10c317da06687dc5a192c493499416ea4916f124d2fc16def8595dd2b903093b946c2bfa1101cd3cd465362b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
